import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Stack } from "@mui/system";
import Background from "@/images/background.png";
import Logo from "@/images/logo.svg";
import Link from "next/link";
import Image from "next/image";
import { UrsorButton } from "ui";
import { Header } from "./components/header";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Stack
          height="100vh"
          width="100vw"
          sx={{
            backgroundImage: `url(${Background.src})`,
            backgroundSize: "cover",
            boxSizing: "border-box",
          }}
          spacing="10px"
        >
          <Header />
          {children}
        </Stack>
      </body>
    </html>
  );
}
